### PR TITLE
cnrfc nbm qpf add date created (version)

### PR DESCRIPTION
**Pull request by jeffsuperglide**

### CODE REVIEW

**Comment by adamscarberry** [comment]
issue: https://github.com/USACE/cumulus/issues/250

**Review by adamscarberry — APPROVED** [review]
unable to verify DSS results as packager doesn't support polar stereographic

**Comment by brettpalmberg** [comment]
> unable to verify DSS results as packager doesn't support polar stereographic

@adamscarberry I'm on it 😎 Stay tuned

**Comment by brettpalmberg** [comment]
Going to merge this PR to incorporate the fix, then circle back with a new PR to address Polar Stereographic.

**Review by brettpalmberg — APPROVED** [review]

**Pull request merged**
