### PR TITLE
Feature/wip polar stereographic

### PR DESCRIPTION
**Pull request by brettpalmberg**
* Alpha version cnrfc-qpe-06h (polar stereographic CRS)
* Remove sample test files from docker image build and mount as volume instead

### CODE REVIEW

**Comment by brettpalmberg** [comment]
Related to USACE/cumulus#323, this should produce productfiles that have a `POLAR_STEREOGRAPHIC` Coordinate Reference System, but can also be downloaded w/ `cumulus_packager`. We should double-check our underlying assumptions with the data provider. Some adjustments to the spatial transformation may still be needed.
 
Alpha level of refinement geoprocessor for: USACE/cumulus#248

**Comment by adamscarberry** [comment]
The packager runs successfully, but with no rain in the region it's hard to confirm results.

**Comment by brettpalmberg** [comment]
> The packager runs successfully, but with no rain in the region it's hard to confirm results.

True!  It looks like CNRFC has archive out there that goes back a ways - I remember CA area experienced a lot of rain a couple weeks back from an atmospheric river. What do you think about setting Airflow to collect past 3 weeks or so to see if we can find some rain for verification?

**Comment by brettpalmberg** [comment]
Merging to incorporate changes into `main`. Will make any additional adjustments via another PR.

**Pull request merged**
